version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"
