services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MINECRAFT_RCON_HOST=${MINECRAFT_RCON_HOST}
      - MINECRAFT_RCON_PORT=${MINECRAFT_RCON_PORT}
      - MINECRAFT_RCON_PASSWORD=${MINECRAFT_RCON_PASSWORD}
    restart: unless-stopped
