version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MINECRAFT_RCON_HOST=${MINECRAFT_RCON_HOST}
      - MINECRAFT_RCON_PORT=${MINECRAFT_RCON_PORT}
      - MINECRAFT_RCON_PASSWORD=${MINECRAFT_RCON_PASSWORD}
      - MINECRAFT_SSH_HOST=${MINECRAFT_SSH_HOST}
      - MINECRAFT_SSH_PORT=${MINECRAFT_SSH_PORT}
      - MINECRAFT_SSH_USERNAME=${MINECRAFT_SSH_USERNAME}
      - MINECRAFT_SSH_PRIVATE_KEY_PATH=${MINECRAFT_SSH_PRIVATE_KEY_PATH}
      - MINECRAFT_LOG_PATH=${MINECRAFT_LOG_PATH}
    volumes:
      - ${MINECRAFT_SSH_PRIVATE_KEY_PATH}:/home/node/.ssh/id_ed25519:ro
    restart: unless-stopped
